version: '3.3'

services:
  todo-app:
    restart: always
    image: eugenia1p/todo_rest:latest
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
