apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment
  namespace: todo-app-ns
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template: 
    metadata:
      labels: 
        app: app
    spec:
      containers:
      - name: app
        image: eugenia1p/todo_go_rest:localhost
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: todo-app-ns
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000