---
- hosts: all
  become: true
  remote_user: "ubuntu"

  tasks:
    - name: Install dependencies for pip3
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - python3-dev
        - python3-setuptools
        - python3-wheel
      become: yes
      
    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install python docker sdk
      shell: |
        pip3 install docker
      become: yes

    - name: Install docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Remove container
      docker_container:
        name: todo-app
        state: absent
    
    - name: Remove image
      docker_image:
        state: absent
        name: eugenia1p/todo_rest
        tag: latest

    - name: Run a docker container
      docker_container:
        name: todo-app
        image: eugenia1p/todo_rest:latest
        restart: always
        ports:
         - "8000:8000"