---
- hosts: all
  become: true
  remote_user: "ubuntu"

  tasks:
    - name: Install dependencies for pip3
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - build-essential
        - python3-distutils
        - python3-dev
        - python3-setuptools
        - python3-wheel
      become: yes
      
    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install python docker sdk
      shell: |
        pip3 install docker
      become: yes

    - name: Install docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Update apt and install docker-compose
      apt:
        name: docker-compose
        state: latest
        update_cache: true

    - name: Copy docker-compose from local to remote
      copy:
        src: ../docker-compose.yml
        dest: ./docker-compose.yml

    - name: Run container
      shell:
        cmd: "docker-compose -f ./docker-compose.yml up -d"
